### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

!pip install numpy

In [1]:
!pip install numpy

In [4]:
import numpy as np

## create array using numpy

# create a 1D array
arr1=np.array([1,2,3,4,5])
print("1D Array:", arr1)
print("Shape of 1D Array:", arr1.shape)
print("Data Type of 1D Array:", arr1.dtype)
print("Type of 1D Array:", type(arr1))

1D Array: [1 2 3 4 5]
Shape of 1D Array: (5,)
Data Type of 1D Array: int64
Type of 1D Array: <class 'numpy.ndarray'>


In [6]:
## 1 D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [8]:
arr3=np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [12]:
# 2D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D Array:\n", arr)
print("Shape of 2D Array:", arr.shape)

2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape of 2D Array: (2, 5)


In [16]:
np.arange(0,10,2).reshape(5,1)  # start, end, step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3,4))  # 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
## Attibutes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Number of Dimensions:", arr.ndim)
print("Shape of Array:", arr.shape)
print("Size of Array:", arr.size)
print("Data Type of Array:", arr.dtype)
print("Item Size (in bytes):", arr.itemsize)
print("Type of Array:", type(arr))


Array:
 [[1 2 3]
 [4 5 6]]
Number of Dimensions: 2
Shape of Array: (2, 3)
Size of Array: 6
Data Type of Array: int64
Item Size (in bytes): 8
Type of Array: <class 'numpy.ndarray'>


In [19]:
## Numpy Vectorized Operations

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
print("Addition:", arr1 + arr2)

# Element-wise subtraction
print("Subtraction:", arr2 - arr1)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr2 / arr1)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


In [20]:
## Universal Function 
arr = np.array([1, 4, 9, 16, 25])

# Square root
print("Square Root:", np.sqrt(arr))

# Exponential
print("Exponential:", np.exp(arr))

# Sine
print("Sine:", np.sin(arr))

# Logarithm
print("Logarithm:", np.log(arr))



Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [21]:
## array Indexing and Slicing

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Original Array:\n", arr)

Original Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [22]:
print(arr[1:, 1:3])  # Slicing rows and columns

[[50 60]
 [80 90]]


In [24]:
print([0][0]) # Accessing specific element

print(arr[0:2,2:]) # Slicing sub-array

0
[[30]
 [60]]


In [26]:
print(arr[0:,0]) # Accessing specific column

[10 40 70]


In [27]:
print(arr[:1,:2]) # Slicing first row and first two columns

[[10 20]]


In [28]:
## statistical concepts --Normalization, 
# Standardization, Mean, Median, Mode, Variance, Standard Deviation

data = np.array([10, 20, 30, 40, 50])

# calculate mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normlized_data = (data - mean)/ std_dev
print("Normalized Data:", normlized_data)


Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean:", mean)

#median
median = np.median(data)
print("Median:", median)



#variance
variance = np.var(data)
print("Variance:", variance)

#standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)



Mean: 5.5
Median: 5.5
Variance: 8.25
Standard Deviation: 2.8722813232690143


In [32]:
# logical operations

data = np.array([10, 25, 30, 45, 50])

# Elements greater than 30
greater_than_30 = data[data > 30]
print("Elements greater than 30:", greater_than_30)

data[((data % 2) == 0) & (data >=10)]  # Even numbers

Elements greater than 30: [45 50]


array([10, 30, 50])